/** Offline HP quiz bank, grouped by book (English, canon terms).
 *  Source: "115 Harry Potter Trivia Questions". Options index 0 is always the
 *  correct answer — QuizSheet shuffles the options before display.
 *  Distractors are deliberately canon-plausible to challenge hardcore fans. */
export type QuizQuestion = { q: string; options: [string, string, string, string] }
export type QuizBook = { key: string; title: string; questions: QuizQuestion[] }

export const QUIZ_BOOKS: QuizBook[] = [
  {
    key: 'general',
    title: 'General',
    questions: [
      { q: 'What magical creature can only be seen by those who have witnessed death?', options: ['Thestral', 'Demiguise', 'Augurey', 'Graphorn'] },
      { q: 'What is Voldemort’s mother’s name?', options: ['Merope Gaunt', 'Walburga Black', 'Eileen Prince', 'Bellatrix Lestrange'] },
      { q: 'What is Harry’s middle name?', options: ['James', 'Sirius', 'Remus', 'Vernon'] },
      { q: 'What is the popular wizarding newspaper based in London?', options: ['The Daily Prophet', 'The Evening Prophet', 'The Quibbler', 'Witch Weekly'] },
      { q: 'What kind of wood is Harry’s first wand made of?', options: ['Holly', 'Yew', 'Vine', 'Elder'] },
      { q: 'Who wrote A History of Magic?', options: ['Bathilda Bagshot', 'Miranda Goshawk', 'Adalbert Waffling', 'Newt Scamander'] },
      { q: 'What are employees of the Department of Mysteries called?', options: ['Unspeakables', 'Obliviators', 'Hit Wizards', 'Unmentionables'] },
      { q: 'What creature guards Gringotts’ deepest vaults?', options: ['A Ukrainian Ironbelly', 'A Hungarian Horntail', 'A Norwegian Ridgeback', 'A Common Welsh Green'] },
      { q: 'What is Hermione’s cat’s name?', options: ['Crookshanks', 'Mrs Norris', 'Tibbles', 'Snowy'] },
      { q: 'What does Harry name his three children?', options: ['James Sirius, Albus Severus & Lily Luna', 'James Sirius, Albus Severus & Lily Molly', 'James Remus, Albus Severus & Lily Luna', 'Sirius James, Severus Albus & Luna Lily'] },
    ],
  },
  {
    key: 'hp1',
    title: '1 · Philosopher’s Stone',
    questions: [
      { q: 'Where does Hagrid first tell Harry that he’s a wizard?', options: ['In a hut on a rock', 'At number four, Privet Drive', 'On the Hogwarts Express', 'In the Leaky Cauldron'] },
      { q: 'What does Harry do to earn a place on the Gryffindor Quidditch team?', options: ['Catches Neville’s Remembrall', 'Outflies Madam Hooch', 'Catches Malfoy’s dropped Snitch', 'Rescues a first-year mid-air'] },
      { q: 'Which obstacle guarding the Stone does Hermione solve?', options: ['Snape’s potion-bottle logic riddle', 'The winged-key chamber', 'The giant chessboard', 'The troll in the dungeon'] },
      { q: 'Which mischievous character from the books never appears in the films?', options: ['Peeves the Poltergeist', 'Nearly Headless Nick', 'Moaning Myrtle', 'The Fat Friar'] },
      { q: 'The Hogwarts motto “Draco dormiens nunquam titillandus” means…', options: ['“Never tickle a sleeping dragon.”', '“Fortune favours the brave.”', '“Knowledge is power, guard it well.”', '“Wisdom is the greatest treasure.”'] },
      { q: 'Who played Dumbledore in the first film?', options: ['Richard Harris', 'Michael Gambon', 'Ian McKellen', 'Jude Law'] },
      { q: 'What is the book’s title everywhere except the United States?', options: ['…and the Philosopher’s Stone', '…and the Sorcerer’s Stone', '…and the Alchemist’s Stone', '…and the Wizard’s Stone'] },
      { q: 'Who discovered the twelve uses of dragon’s blood?', options: ['Albus Dumbledore', 'Nicolas Flamel', 'Newt Scamander', 'Bathilda Bagshot'] },
      { q: 'In what year was Harry Potter and the Sorcerer’s Stone released in the US?', options: ['1998', '1997', '1999', '2001'] },
      { q: 'How many presents did Dudley receive on his birthday in total?', options: ['38', '36', '37', '40'] },
      { q: 'What was the Fat Lady’s password into the Gryffindor common room?', options: ['Caput Draconis', 'Fortuna Major', 'Pig snout', 'Balderdash'] },
      { q: 'What is the first line of the book?', options: ['“Mr and Mrs Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much.”', '“Nearly ten years had passed since the Dursleys found their nephew on the doorstep.”', '“The Dursleys of number four were perfectly ordinary people, and proud of it.”', '“Not for the first time, an argument had broken out over breakfast at number four.”'] },
      { q: 'Where does Harry first see Draco Malfoy?', options: ['In Madam Malkin’s Robes for All Occasions', 'In Ollivanders', 'On the Hogwarts Express', 'In Flourish and Blotts'] },
      { q: 'What do the Dursleys give Harry for Christmas?', options: ['A 50-pence piece', 'A single tissue', 'A used toothpick', 'A bent coat hanger'] },
      { q: 'Which real library served as the Hogwarts restricted section on film?', options: ['The Bodleian Library, Oxford', 'Trinity College Library, Dublin', 'The John Rylands Library', 'Christ Church Library'] },
    ],
  },
  {
    key: 'hp2',
    title: '2 · Chamber of Secrets',
    questions: [
      { q: 'In the book (not the film), who explains the origins of the Chamber of Secrets?', options: ['Professor Binns', 'Professor Dumbledore', 'Nearly Headless Nick', 'Professor Dippet'] },
      { q: 'Why does Neville faint in Herbology class?', options: ['His earmuffs slipped and he heard the mandrake’s cry', 'He forgot his earmuffs entirely', 'A Venomous Tentacula grabbed him', 'The greenhouse fumes overwhelmed him'] },
      { q: 'On what date do the Weasleys rescue Harry from Privet Drive?', options: ['31 July — his birthday', '1 September', '30 July', '24 December'] },
      { q: 'Who removes all the bones from Harry’s arm?', options: ['Gilderoy Lockhart', 'Madam Pomfrey', 'Severus Snape', 'Dobby'] },
      { q: 'Who steals the Polyjuice ingredients from Snape’s office?', options: ['Hermione', 'Harry', 'Ron', 'Fred'] },
      { q: 'Hermione is found Petrified alongside which student?', options: ['Penelope Clearwater', 'Colin Creevey', 'Justin Finch-Fletchley', 'Ginny Weasley'] },
      { q: 'Which office does Arthur Weasley work for?', options: ['Misuse of Muggle Artefacts Office', 'Department of Mysteries', 'Department of Magical Law Enforcement', 'Muggle-Worthy Excuse Committee'] },
      { q: 'How many Muggles see the flying Ford Anglia on the way to school?', options: ['Seven', 'Six', 'Eight', 'Nine'] },
      { q: 'What is Gilderoy Lockhart’s favourite colour?', options: ['Lilac', 'Lavender', 'Turquoise', 'Gold'] },
      { q: 'What is the cure for being Petrified?', options: ['Mandrake Restorative Draught', 'Phoenix tears', 'A bezoar', 'Essence of Dittany'] },
      { q: 'Who was headmaster when Tom Riddle was a student?', options: ['Armando Dippet', 'Albus Dumbledore', 'Phineas Nigellus Black', 'Everard'] },
      { q: 'What is Gilderoy Lockhart’s autobiography called?', options: ['Magical Me', 'Marvellous Me', 'Gadding with Ghouls', 'Year with the Yeti'] },
      { q: 'Where does Harry first begin hearing the voice no one else can hear?', options: ['In Lockhart’s office, during detention', 'In the Great Hall', 'In the Gryffindor common room', 'In the Chamber itself'] },
    ],
  },
  {
    key: 'hp3',
    title: '3 · Prisoner of Azkaban',
    questions: [
      { q: 'Who is Stan Shunpike?', options: ['The conductor of the Knight Bus', 'The driver of the Knight Bus', 'The barman at the Leaky Cauldron', 'A Ministry official'] },
      { q: 'Who plays Dumbledore from this film onward?', options: ['Michael Gambon', 'Richard Harris', 'Ian McKellen', 'John Hurt'] },
      { q: 'How many classes did Hermione take this year?', options: ['12', '10', '11', '13'] },
      { q: 'In the book, who is Hufflepuff’s Seeker against Gryffindor?', options: ['Cedric Diggory', 'Zacharias Smith', 'Ernie Macmillan', 'Cho Chang'] },
      { q: 'In the book, who becomes temporary guard after the Fat Lady’s portrait is slashed?', options: ['Sir Cadogan', 'The Fat Friar', 'The Grey Lady', 'Violet'] },
      { q: 'Whom does Harry overhear in the Three Broomsticks discussing Sirius Black?', options: ['Flitwick, McGonagall, Hagrid, Fudge & Madam Rosmerta', 'Dumbledore, McGonagall & Madam Rosmerta', 'Fudge, Snape & Madam Rosmerta', 'McGonagall, Hagrid & Lupin'] },
      { q: 'Why do Ron and Hermione stop speaking?', options: ['Ron blames Crookshanks for Scabbers’ disappearance', 'Hermione reported his Firebolt to McGonagall', 'A row over house-elf rights', 'Hermione dropped Divination'] },
      { q: 'What does Aunt Marge do for a living?', options: ['Breeds bulldogs', 'Breeds Crups', 'Runs a Kneazle kennel', 'Trains guard dogs'] },
      { q: 'In the film, what sound does Ron make after eating a magical sweet?', options: ['A lion’s roar', 'A canary’s chirp', 'A frog’s croak', 'A dog’s bark'] },
      { q: 'What is Parvati’s Boggart?', options: ['A mummy (book) / a giant cobra (film)', 'A snake (book) / a mummy (film)', 'A banshee (book) / a mummy (film)', 'A mummy (book) / a giant spider (film)'] },
      { q: 'In the book, how does Riddikulus defeat Parvati’s Boggart?', options: ['The mummy trips on its own wrappings', 'Its bandages unravel into ribbons', 'It turns into a jack-in-the-box', 'It shrinks into a toy'] },
      { q: 'At the start of the story, where does Hedwig find Harry?', options: ['In his room at the Leaky Cauldron', 'At Privet Drive', 'At the Burrow', 'In Diagon Alley'] },
      { q: 'On Neville’s Boggart-Snape, dressed in his gran’s clothes, what bird tops the hat?', options: ['A vulture', 'A stuffed raven', 'A red-feathered parrot', 'An owl'] },
      { q: 'When Snape takes over Lupin’s class, which page does he tell students to turn to?', options: ['394', '349', '493', '934'] },
      { q: 'A Hippogriff is a mix of which two creatures?', options: ['Horse and eagle', 'Lion and eagle', 'Horse and hawk', 'Griffin and horse'] },
      { q: 'How much gold do the Weasleys win in the Daily Prophet Grand Prize Galleon Draw?', options: ['700 Galleons', '500 Galleons', '1,000 Galleons', '100 Galleons'] },
      { q: 'Where do the Weasleys holiday with their winnings?', options: ['Egypt', 'Romania', 'France', 'Bulgaria'] },
    ],
  },
  {
    key: 'hp4',
    title: '4 · Goblet of Fire',
    questions: [
      { q: 'What is Fleur Delacour’s little sister’s name?', options: ['Gabrielle', 'Gabriella', 'Apolline', 'Nymphadora'] },
      { q: 'Who can turn into a beetle at will?', options: ['Rita Skeeter', 'Dolores Umbridge', 'Bathilda Bagshot', 'Sybill Trelawney'] },
      { q: 'Which two nations contest the Quidditch World Cup Final?', options: ['Ireland and Bulgaria', 'England and Bulgaria', 'Ireland and Egypt', 'Bulgaria and Luxembourg'] },
      { q: 'Which beloved Hogwarts activity is cancelled because of the Triwizard Tournament?', options: ['Quidditch', 'Hogsmeade visits', 'Care of Magical Creatures', 'The end-of-year feast'] },
      { q: 'Who grows a long beard trying to cheat their way into the Tournament?', options: ['Fred and George Weasley', 'Lee Jordan and the twins', 'Angelina Johnson', 'Seamus Finnigan'] },
      { q: 'Which important characters appear in the book but not the film?', options: ['The Dursleys', 'The Malfoys', 'Bill and Charlie Weasley', 'The Longbottoms'] },
      { q: 'Members of which two UK bands played the Weird Sisters at the Yule Ball?', options: ['Pulp and Radiohead', 'Blur and Oasis', 'Coldplay and Muse', 'Franz Ferdinand and Kaiser Chiefs'] },
      { q: 'How does Cedric defeat his dragon in the first task?', options: ['Transfigures a rock into a dog to distract it', 'Summons his broom', 'Conjures a curtain of flame', 'Casts the Conjunctivitis Curse'] },
      { q: 'What is Mad-Eye Moody’s catchphrase?', options: ['“CONSTANT VIGILANCE!”', '“Eternal watchfulness!”', '“Vigilance always!”', '“Trust no one!”'] },
      { q: 'Which maze challenge was left out of the films?', options: ['The Sphinx’s riddle', 'The Acromantula', 'The enchanted hedge', 'The golden mist'] },
      { q: 'Which of Fred and George’s sweets does Dudley eat?', options: ['Ton-Tongue Toffee', 'Canary Cream', 'Puking Pastille', 'Fainting Fancy'] },
      { q: 'What does Mad-Eye Moody turn Draco into?', options: ['A ferret', 'A weasel', 'A stoat', 'A rat'] },
      { q: 'Which Quidditch team did Ludo Bagman play for?', options: ['Wimbourne Wasps', 'Montrose Magpies', 'Appleby Arrows', 'Chudley Cannons'] },
      { q: 'What position did Bagman play?', options: ['Beater', 'Keeper', 'Chaser', 'Seeker'] },
      { q: 'What is Ron’s role in S.P.E.W.?', options: ['Treasurer', 'Secretary', 'President', 'Vice-President'] },
    ],
  },
  {
    key: 'hp5',
    title: '5 · Order of the Phoenix',
    questions: [
      { q: 'Which exciting moment from the book is cut from the film?', options: ['Gryffindor winning the Quidditch Cup', 'Harry’s first kiss', 'The Weasley twins leaving Hogwarts', 'Dumbledore’s escape'] },
      { q: 'What crime triggers Harry’s disciplinary hearing at the Ministry?', options: ['Casting the Patronus Charm in front of a Muggle', 'Underage Apparition', 'Blowing up Aunt Marge', 'Inflating a car with magic'] },
      { q: 'Which two students coin the name “Dumbledore’s Army”?', options: ['Cho Chang and Ginny Weasley', 'Hermione and Ginny', 'Fred and George', 'Luna and Neville'] },
      { q: 'Which of Harry’s dorm-mates admits he doesn’t believe Voldemort is back?', options: ['Seamus Finnigan', 'Dean Thomas', 'Ernie Macmillan', 'Zacharias Smith'] },
      { q: 'What is Draco Malfoy’s mother’s name?', options: ['Narcissa', 'Bellatrix', 'Andromeda', 'Druella'] },
      { q: 'Which animal is Dolores Umbridge obsessed with?', options: ['Cats (kittens)', 'Owls', 'Toads', 'Puffskeins'] },
      { q: 'In the book, what sport has Dudley recently taken up?', options: ['Boxing', 'Rugby', 'Wrestling', 'Football'] },
      { q: 'What is Hagrid’s half-brother’s name?', options: ['Grawp', 'Golgomath', 'Karkus', 'Fridwulfa'] },
      { q: 'How does Dumbledore escape his office when the Ministry comes for him?', options: ['He grabs Fawkes’s tail and vanishes in flame', 'He Disapparates', 'He uses a Portkey', 'He slips under an Invisibility Cloak'] },
      { q: 'Where do Harry and Cho share their first kiss?', options: ['In the Room of Requirement', 'Under the mistletoe in a corridor', 'In the Great Hall', 'By the lake'] },
      { q: 'What is the address of the Order of the Phoenix’s headquarters?', options: ['12 Grimmauld Place, London', '12 Spinner’s End', '4 Privet Drive', 'Shell Cottage'] },
      { q: 'What did Sirius’s mother do to his name on the family tapestry?', options: ['Burned it away', 'Crossed it out in ink', 'Tore the fabric', 'Stitched over it'] },
      { q: 'What do the trio find in a locked cabinet at headquarters?', options: ['A Boggart', 'A Hand of Glory', 'A cursed necklace', 'A Sneakoscope'] },
      { q: 'Hermione jinxes the DA sign-up parchment. What befalls a traitor?', options: ['Pustules spell “SNEAK” across their face', 'They lose their voice', 'Boils spell “traitor” on their hands', 'Their tongue swells shut'] },
      { q: 'Which old acquaintance do they meet at St Mungo’s?', options: ['Gilderoy Lockhart', 'Professor Quirrell', 'Bertha Jorkins', 'Broderick Bode'] },
    ],
  },
  {
    key: 'hp6',
    title: '6 · Half-Blood Prince',
    questions: [
      { q: 'Who brews a love potion for Harry that Ron eats by mistake?', options: ['Romilda Vane', 'Lavender Brown', 'Pansy Parkinson', 'Katie Bell'] },
      { q: 'Who is Ron’s actual love interest this year?', options: ['Lavender Brown', 'Hermione Granger', 'Padma Patil', 'Fleur Delacour'] },
      { q: 'Which Horcrux that Harry and Dumbledore retrieve turns out to be a fake?', options: ['Slytherin’s locket', 'Hufflepuff’s cup', 'Ravenclaw’s diadem', 'Marvolo’s ring'] },
      { q: 'What is Fred and George’s shop called?', options: ['Weasleys’ Wizard Wheezes', 'Zonko’s Joke Shop', 'Gambol and Japes', 'Weasleys’ Wildfire Whiz-bangs'] },
      { q: 'Who teaches Potions this year?', options: ['Horace Slughorn', 'Severus Snape', 'Pomona Sprout', 'Septima Vector'] },
      { q: 'What are the gemstones in the cursed necklace from Borgin and Burkes?', options: ['Opals', 'Emeralds', 'Rubies', 'Sapphires'] },
      { q: 'Which spell that Snape invented does Harry later use on Draco?', options: ['Sectumsempra', 'Levicorpus', 'Langlock', 'Confringo'] },
      { q: 'What does Hermione smell in the Amortentia?', options: ['Fresh grass, new parchment, spearmint toothpaste (and Ron’s hair)', 'Treacle tart, broomstick handle, the Burrow', 'Fresh parchment, old books and Ron’s hair', 'Grass, firewhisky and Ron’s hair'] },
      { q: 'Which is the longest film in the series?', options: ['Chamber of Secrets (161 min)', 'Deathly Hallows: Part 2', 'Order of the Phoenix', 'Goblet of Fire'] },
      { q: 'Lily once turned a lily into a goldfish for Slughorn. What was it named?', options: ['Francis', 'Frederick', 'Ferdinand', 'Fitzgerald'] },
      { q: 'How many Horcruxes have been destroyed by the end of this story?', options: ['Two: the diary and the ring', 'One: the diary', 'Three', 'Four'] },
      { q: 'Who is the Half-Blood Prince?', options: ['Severus Snape', 'Tom Riddle', 'Draco Malfoy', 'Regulus Black'] },
      { q: 'What do the hands of the Weasleys’ clock point to when Harry reaches the Burrow?', options: ['“Mortal peril”', '“Lost”', '“Prison”', '“Home”'] },
      { q: 'Who features in the first Pensieve memory Dumbledore shows Harry?', options: ['Bob Ogden', 'Caractacus Burke', 'Morfin Gaunt', 'Horace Slughorn'] },
      { q: 'What are the three D’s of successful Apparition?', options: ['Destination, determination, deliberation', 'Direction, determination, desire', 'Destination, desire, deliberation', 'Determination, direction, delivery'] },
    ],
  },
  {
    key: 'hp7',
    title: '7 · Deathly Hallows',
    questions: [
      { q: 'Who loses an ear at the start of the book?', options: ['George Weasley', 'Fred Weasley', 'Bill Weasley', 'Percy Weasley'] },
      { q: 'Which four characters serve as Minister of Magic across the series?', options: ['Fudge, Scrimgeour, Thicknesse & Shacklebolt', 'Fudge, Crouch, Scrimgeour & Shacklebolt', 'Fudge, Scrimgeour, Umbridge & Shacklebolt', 'Fudge, Bagman, Thicknesse & Shacklebolt'] },
      { q: 'In the epilogue, who says, “Don’t let it worry you. It’s me, I’m extremely famous.”', options: ['Ron Weasley', 'Harry Potter', 'George Weasley', 'Draco Malfoy'] },
      { q: 'In the film, who gives Draco Malfoy an awkward hug?', options: ['Voldemort', 'Narcissa Malfoy', 'Bellatrix Lestrange', 'Lucius Malfoy'] },
      { q: 'Which is the shortest film in the series?', options: ['Deathly Hallows: Part 2 (130 min)', 'Philosopher’s Stone', 'Half-Blood Prince', 'Deathly Hallows: Part 1'] },
      { q: 'Which character rides a broom for the first time in this film?', options: ['Hermione Granger', 'Neville Longbottom', 'Luna Lovegood', 'Ginny Weasley'] },
      { q: 'On what date did the Battle of Hogwarts end with Voldemort’s death?', options: ['2 May 1998', '2 May 1997', '1 May 1998', '31 July 1998'] },
      { q: 'What is the name of Bill and Fleur’s house?', options: ['Shell Cottage', 'The Burrow', 'Spinner’s End', 'Chorley Cottage'] },
      { q: 'What fake illness does Ron claim to explain his absence from Hogwarts?', options: ['Spattergroit', 'Dragon pox', 'Scrofungulus', 'Vanishing sickness'] },
      { q: 'What does Harry steal from Umbridge’s office at the Ministry?', options: ['Mad-Eye Moody’s magical eye', 'Slytherin’s locket', 'The Muggle-born Registration files', 'A blood quill'] },
      { q: 'What is Luna Lovegood’s father’s name?', options: ['Xenophilius', 'Xenophon', 'Newton', 'Pandaros'] },
      { q: 'Who was in love with Helena Ravenclaw?', options: ['The Bloody Baron', 'The Fat Friar', 'Nearly Headless Nick', 'The Grey Friar'] },
      { q: 'In the book, where do Hermione’s parents move to?', options: ['Australia', 'New Zealand', 'Canada', 'France'] },
      { q: 'What is Snape’s Patronus?', options: ['A doe', 'A stag', 'A wolf', 'A phoenix'] },
      { q: 'What is the last line of the final book?', options: ['“All was well.”', '“Mischief managed.”', '“The scar had not pained Harry for nineteen years.”', '“And then they were home.”'] },
    ],
  },
]

/** Flat list of every question — used for any all-books mode. */
export const ALL_QUIZ_QUESTIONS: QuizQuestion[] = QUIZ_BOOKS.flatMap((b) => b.questions)
